apiVersion: v1
kind: Service
metadata:
  name: clustercontrol-external
  labels:
    app: clustercontrol-external
spec:
  type: NodePort
  ports:
  - name: http
    nodePort: 30080
    port: 80
  - name: https
    nodePort: 30443
    port: 443
  selector:
    app: clustercontrol
---
apiVersion: v1
kind: Service
metadata:
  name: clustercontrol
  labels:
    app: clustercontrol
spec:
  type:
  ports:
  - name: mysql
    port: 3306
    protocol: TCP
    targetPort: 3306
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: clustercontrol
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: clustercontrol
  labels:
    app: clustercontrol
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: clustercontrol
    spec:
      containers:
      - name: clustercontrol
        image: severalnines/clustercontrol
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        - name: cmon-rpc
          containerPort: 9500
        - name: cmon-rpc-tls
          containerPort: 9501
        - name: cmon-events
          containerPort: 9510
        - name: cmon-ssh
          containerPort: 9511
        - name: cmon-mysql
          containerPort: 3306
        - name: cmon-cloud
          containerPort: 9518
        readinessProbe:
          exec:
            command:
            - curl
            - -sSf
            - http://localhost/clustercontrol/
          initialDelaySeconds: 60
          periodSeconds: 1
        volumeMounts:
        - name: mysql-datadir
          mountPath: /var/lib/mysql
        - name: cc-cmond
          mountPath: /etc/cmon.d
        - name: cc-ssh
          mountPath: /root/.ssh
        - name: db-backups
          mountPath: /backups
      volumes:
      - name: mysql-datadir
        persistentVolumeClaim:
          claimName: datadir-cc-nfs-pv1
      - name: cc-cmond
        persistentVolumeClaim:
          claimName: cmond-cc-nfs-pv2
      - name: cc-ssh
        persistentVolumeClaim:
          claimName: ssh-cc-nfs-pv3
      - name: db-backups
        persistentVolumeClaim:
          claimName: backups-cc-nfs-pv4
